# Dev Mainnet tests
name: DEV Mainnet tests

on:
  schedule:
    - cron: '0 9 * * *' # everyday at 9am
    - cron: '0 23 * * *' # everyday at 11pm

env:
  TERRA_MAINNET_URL: ${{ secrets.VUE_APP_TERRA_MAINNET_URL }}
  AVALANCHE_MAINNET_NODE: ${{ secrets.VUE_APP_AVALANCHE_MAINNET_NODE }}
  AVALANCHE_TESTNET_NODE: ${{ secrets.VUE_APP_AVALANCHE_TESTNET_NODE }}
  NEAR_MAINNET_URL: ${{ secrets.VUE_APP_NEAR_MAINNET_URL }}
  SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
  TWENTY_FOUR_SEEDS: ${{ secrets.TWENTY_FOUR_SEEDS }}
  TEST_WALLET_PASSWORD: ${{ secrets.TEST_WALLET_PASSWORD }}

jobs:
  regressiontest_dev_mainnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2.5.1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: '14'
        # Create screenshots directory
      - run: mkdir screenshots

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - run: |
          echo VUE_APP_TERRA_MAINNET_URL =$TERRA_MAINNET_URL >> .env
          echo VUE_APP_AVALANCHE_MAINNET_NODE =$AVALANCHE_MAINNET_NODE >> .env
          echo VUE_APP_AVALANCHE_TESTNET_NODE =$AVALANCHE_TESTNET_NODE >> .env
          echo VUE_APP_NEAR_MAINNET_URL =$NEAR_MAINNET_URL >> .env

      # Create Dev Wallet for nightly tests
      - name: Set development manifest
        run: |
          export NODE_OPTIONS="--max-old-space-size=5120"
          jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
          mv ./src/manifest.tmp ./src/manifest.json
          yarn install
          yarn lint
          yarn build

      - name: Regression tests against Mainnet
        uses: beemi/puppeteer-headful@v1.0.11
        env:
          CI: 'true'
          DISPLAY: :99
        with:
          args: yarn test:mainnet:devagent # Run tests against dev mainnet

      - name: Save Screenshots
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore
